export const RAW_LOCATIONS = [
  "01-BAHAN BAKU-KTP",
  "02-BAHAN BAKU-DPK",
  "03-BAHAN BAKU-BGR",
];

export const PACKAGING_LOCATIONS = [
  "10-KEMASAN-KTP",
  "11-KEMASAN-DPK",
  "12-KEMASAN-BGR",
];

export const PRODUCTION_LOCATIONS = [
  "04-PRODUKSI-KTP",
  "05-PRODUKSI-DPK",
  "06-PRODUKSI-BGR",
];

export const ONLINE_PACKING_LOCATIONS = [
  "04-ONLINE PACKING-KTP",
  "05-ONLINE PACKING-DPK",
  "06-ONLINE PACKING-BGR",
];

export const SPEEDSHOP_LOCATIONS = [
  "07-SPEEDSHOP-KTP",
  "08-SPEEDSHOP-DPK",
  "09-SPEEDSHOP-BGR",
];

export const PRODUCT_LOCATIONS = [
  ...ONLINE_PACKING_LOCATIONS
];

